import { tabs } from './parts/tabs';
import { related } from './parts/related';
import { articles } from './parts/articles';
import { main } from './parts/main';
import { pointer } from './parts/pointer';
import { dividers } from './parts/dividers';
import { together } from './parts/together';
import { header } from './parts/header';
import { toTop } from './parts/footer';
import { galCar } from './parts/accordeon';
import { team } from './parts/team';
import { talent } from './parts/talent';
import { reviews } from './parts/reviews';
import { allservices } from './parts/allservices';
import { superSec } from './parts/super';
import './parts/clipboard';
import './parts/preloader';
import './parts/sidebar';
// import './parts/policy';

header();
main();
tabs();
dividers();
pointer();
related();
articles();
together();
toTop();
galCar();
team();
talent();
reviews();
allservices();
superSec();
